### ISSUE TITLE
getting design issue in firefox and safari 

### ISSUE THREAD

**Issue by Sanaullahbugti** [wojtekmaj/react-time-picker#142]
firefox and safari
![image](https://user-images.githubusercontent.com/39256766/182093021-fb948538-79b7-482f-819e-27dd86637962.png)
chrome is working fine 
![image](https://user-images.githubusercontent.com/39256766/182093162-5971d0cb-1a79-464a-a287-10125eaecd52.png)

**Comment by wojtekmaj** [comment]
Do you use default CSS and write your customizations on top of that or did you write the CSS from scratch? Because I can't reproduce this with default styling.

This is the most important bit from the default CSS:

https://github.com/wojtekmaj/react-time-picker/blob/6c4ff749968a2e4af1ae7918c95250b1e52557fe/src/TimePicker.less#L49-L55
